PluginPrefix: '§3[§bFunctions§3] '
ServerName: Unknown Server
Language: en
Updated:
  DownloadEnable: true
  CheckTime_minutes: 10
  CheckEnable: true
List:
  Group:
  - Default
  - VIP
  - OP
ServerIcon:
- server-icon.png
- serviceModeIcon.png
